# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'SeeFood_IBM' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SeeFood_IBM
    pod 'IBMWatsonAssistantV1', '~> 2.0.1'
    pod 'IBMWatsonAssistantV2', '~> 2.0.1'
    pod 'IBMWatsonCompareComplyV1', '~> 2.0.1'
    pod 'IBMWatsonDiscoveryV1', '~> 2.0.1'
    pod 'IBMWatsonLanguageTranslatorV3', '~> 2.0.1'
    pod 'IBMWatsonNaturalLanguageClassifierV1', '~> 2.0.1'
    pod 'IBMWatsonNaturalLanguageUnderstandingV1', '~> 2.0.1'
    pod 'IBMWatsonPersonalityInsightsV3', '~> 2.0.1'
    pod 'IBMWatsonSpeechToTextV1', '~> 2.0.1'
    pod 'IBMWatsonTextToSpeechV1', '~> 2.0.1'
    pod 'IBMWatsonToneAnalyzerV3', '~> 2.0.1'
    pod 'IBMWatsonVisualRecognitionV3', '~> 2.0.1'
    pod 'SVProgressHUD'
end
